### ISSUE TITLE
accept URLs for schemas

### ISSUE THREAD

**Issue by nsheff** [pepkit/eido#10]
eido should accept a URL for the schema:

```
eido -p example/cfg.yaml -s http://schemas.databio.org/bed_maker.yaml Reading sample annotations sheet: '/home/nsheff/code/bedmaker/example/samples_to_convert.csv'
Storing sample table from file '/home/nsheff/code/bedmaker/example/samples_to_convert.csv'
Traceback (most recent call last):
  File "/home/nsheff/.local/bin/eido", line 8, in <module>
    sys.exit(main())
  File "/home/nsheff/.local/lib/python3.7/site-packages/eido/eido.py", line 199, in main
    validate_project(p, args.schema, args.exclude_case)
  File "/home/nsheff/.local/lib/python3.7/site-packages/eido/eido.py", line 126, in validate_project
    schema_dict = _read_schema(schema=schema)
  File "/home/nsheff/.local/lib/python3.7/site-packages/eido/eido.py", line 97, in _read_schema
    raise TypeError("schema has to be either a dict or a path to an existing file")
TypeError: schema has to be either a dict or a path to an existing file
```

I've just done something similar in henge. Perhaps we should move this function into `ubiquerg`:

https://github.com/databio/henge/blob/cae29759ae3fe7fa009d4f888e3f8cd69db0f165/henge/henge.py#L218-L240

**Comment by nsheff** [comment]
or maybe it belongs in yacman.... can eido require yacman? right now you're not using it...

**Comment by nsheff** [comment]
I meant to put this onto dev... sorry
