### ISSUE TITLE
Warn if bad filter

### ISSUE THREAD

**Issue by nsheff** [pepkit/eido#29]
Giving a bogus filter fails silently:

```
eido convert https://raw.githubusercontent.com/databio/bedshift_analysis/master/pep_main/project_config.yaml -f bogus_filter
```

It should instead say `bogus filter not found. options are: {filters}`. Or something.

**Comment by stolarczyk** [comment]
I think you're running an outdated version, it raises an error  in my hands:

```
[mstolarczyk@MichalsMBP eido](dev): eido convert https://raw.githubusercontent.com/pepkit/nf-core-pep/master/config.yaml -f test
Traceback (most recent call last):
  File "/usr/local/bin/eido", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/site-packages/eido/cli.py", line 79, in main
    convert_project(p, args.format)
  File "/usr/local/lib/python3.9/site-packages/eido/conversion.py", line 30, in convert_project
    run_filter(prj, target_format)
  File "/usr/local/lib/python3.9/site-packages/eido/conversion.py", line 45, in run_filter
    raise ValueError(
ValueError: Requested filter (test) not found. Available: basic, csv, yaml, yaml-samples
```

**Comment by nsheff** [comment]
works.
