### ISSUE TITLE
Cryptic error message when converting to csv

### ISSUE THREAD

**Issue by Redmar-van-den-Berg** [pepkit/eido#75]
Whey I try to convert a PEP project to csv using eido, I get the following error. Is there a way to figure out what is going wrong here, I have no idea what could be wrong. As far as I can tell, there is nothing out of the ordinary about this project.

```python
eido convert project_config.yml --format csv
Traceback (most recent call last):
  File "micromamba/envs/PEP/bin/eido", line 10, in <module>
    sys.exit(main())
             ^^^^^^
  File "micromamba/envs/PEP/lib/python3.12/site-packages/eido/cli.py", line 92, in main
    p = Project(args.pep, sample_table_index=args.st_index)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "micromamba/envs/PEP/lib/python3.12/site-packages/peppy/project.py", line 163, in __init__
    self.create_samples(modify=False if self[SAMPLE_TABLE_FILE_KEY] else True)
  File "micromamba/envs/PEP/lib/python3.12/site-packages/peppy/project.py", line 277, in create_samples
    self.modify_samples()
  File "micromamba/envs/PEP/lib/python3.12/site-packages/peppy/project.py", line 462, in modify_samples
    self.attr_imply()
  File "micromamba/envs/PEP/lib/python3.12/site-packages/peppy/project.py", line 818, in attr_imply
    if sample_val not in implier_val:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by nsheff** [comment]
@khoroshevskyi can you look into this?

**Comment by nsheff** [comment]
@Redmar-van-den-Berg is there any way you can share the PEP?

Can you put the PEP on PEPhub?

**Comment by khoroshevskyi** [comment]
@Redmar-van-den-Berg, As Nathan mentioned, could you provide provide sample PEP, because unfortunately, I can't reproduce this error

**Comment by nsheff** [comment]
@khoroshevskyi it looks like the problem is in:

```
if sample_val not in implier_val:
```

can you try maybe making an example table with an implied attribute, but where a particular sample has a value that is not in the set of "if" values for the implied attribute?

Maybe we don't have a good error message capturing this annotation error.

**Comment by khoroshevskyi** [comment]
I already did it, and I haven't found any issues.
Also, try to update eido to newer version, it seems that it is old peppy, and eido, and this issue could be solved in previous release

**Comment by nsheff** [comment]
@Redmar-van-den-Berg can you let us know what version you're using, and try updating to the latest version?

**Comment by Redmar-van-den-Berg** [comment]
I wasn't able to determine exactly what was wrong with the PEP project, but I no longer get this error after upgrading to eido 0.2.4.
